### ISSUE TITLE
Remove the "remove id" feature

### ISSUE THREAD

**Issue by obiwarn** [yogiben/meteor-admin#262]
when I edit a document the admin removes the id from the field name.
this is not intended in some cases.

e.g. document from collection bookings with fields:

spot
spotId
spotName

In the mask of the admin it shows:

Spot
Spot
Spot name

**Comment by basilkohler** [comment]
If a label in a SimpleSchema is not specified it gets auto generated with the information from the key.
One of the behaviours is to remove the 'Id' because that usually makes sense (e.g. AuthorId is probably the Author field).You should be able to fix this by using an explicit label for the key in the SimpleSchema in question.

**Comment by obiwarn** [comment]
@basilkohler Thank yo very much!
