### ISSUE TITLE
Datepicker issue 

### ISSUE THREAD

**Issue by dgrabla** [yogiben/meteor-admin#5]
Fields that are define as dates should open a "Datetime" picker on the Admin panel

Car = new SimpleSchema({
  adquiredAt: {
    type: Date
  }
});

**Comment by taromero** [comment]
Hi @yogiben this is unnrelated to the issue, but on https://github.com/yogiben/meteor-admin/issues/5#issuecomment-56648345 I see you have customized the datepicker to show the date on a `dd/mm/yyyy` format. By default I'm seeing the format as `mm/dd/yyyy`, how can I change that?

**Comment by miri-am** [comment]
Did anybody have success with this? I added the datetime picker package: https://atmospherejs.com/aldeed/autoform-bs-datetimepicker

and used the following  schema but when I do this it just renders an empty input field with no date picker at all.

```
Schemas.Example = new SimpleSchema({
    lastUpdated: {
        type: Date,
        autoform: {
          afFieldInput: {
            type: "bootstrap-datetimepicker"
          }
      }
    }
}
```

**Comment by logvik** [comment]
@miri-am From Documentation:
To use the bootstrap-datetimepicker input type, add the **aldeed:autoform-bs-datetimepicker** package to your app. You must also add the [bootstrap-datetimepicker library javascript](http://eonasdan.github.io/bootstrap-datetimepicker/) in your /client/lib folder or add the **tsega:bootstrap3-datetimepicker** Meteor package to your app. And of course you must be using Bootstrap 3. See the full documentation [here](https://github.com/aldeed/meteor-autoform-bs-datetimepicker).
Please, check complying with the conditions and console of browser, because I have been receiving something like $.datetimepicker is undefined
